### ISSUE TITLE
Add notice about the new monorepo to the README. 

### ISSUE THREAD

**Issue by mewmew** [azul3d-legacy/issues#42]
This should probably be done for each of the Azul3d legacy repositories. However this one in particular is especially important, as github.com/azul3d/issues points here and not github.com/azul3d/engine/issues which is the appropriate place.

**Comment by slimsag** [comment]
Agreed, I'll see if I can get to this soon.

**Comment by slimsag** [comment]
For now I updated the README of this repo, I'll see what I can do about the others later.

**Comment by mewmew** [comment]
Perfect!

**Comment by mewmew** [comment]
The all caps `MOVED` headline should be enough to help users find the right issue tracker. And since no new issues have been reported in this meta-repository for quite some time, it looks like we may safely close this issue for now.
